version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: casino
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - casino-net

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      DB_NAME: casino
      PORT: 3000
    depends_on:
      - db
    networks:
      - casino-net

  frontend:
    # EL TRUCO MAGICO: Docker descargará el frontend directo de tu otro repo
    build: https://github.com/Moonlighpoio/frontend_intro_devops_casino.git
    ports:
      - "80:8080"
    environment:
      # Conecta por la red interna al servicio backend de arriba
      BACKEND_HOST: "backend:3000"
    depends_on:
      - backend
    networks:
      - casino-net

networks:
  casino-net:

volumes:
  pg_data:
